version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: ensolvers-postgres
    environment:
      POSTGRES_DB: ensolvers_db
      POSTGRES_USER: ensolvers_user
      POSTGRES_PASSWORD: ensolvers_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - ensolvers-network

volumes:
  postgres_data:

networks:
  ensolvers-network:
